//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Behk3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состав блюда.
    /// </summary>
    // *** Start programmer edit section *** (СоставБлюда CustomAttributes)

    // *** End programmer edit section *** (СоставБлюда CustomAttributes)
    [AutoAltered()]
    [Caption("Состав блюда")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставБлюдаE", new string[] {
            "Количество as \'Количество\'",
            "Ингредиенты as \'Ингредиенты\'",
            "Ингредиенты.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Ингредиенты.Наименование"})]
    [MasterViewDefineAttribute("СоставБлюдаE", "Ингредиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class СоставБлюда : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.Behk3.Ингредиенты fИнгредиенты;
        
        private IIS.Behk3.Питания fПитания;
        
        // *** Start programmer edit section *** (СоставБлюда CustomMembers)

        // *** End programmer edit section *** (СоставБлюда CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (СоставБлюда.Количество CustomAttributes)

        // *** End programmer edit section *** (СоставБлюда.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (СоставБлюда.Количество Get start)

                // *** End programmer edit section *** (СоставБлюда.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (СоставБлюда.Количество Get end)

                // *** End programmer edit section *** (СоставБлюда.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставБлюда.Количество Set start)

                // *** End programmer edit section *** (СоставБлюда.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (СоставБлюда.Количество Set end)

                // *** End programmer edit section *** (СоставБлюда.Количество Set end)
            }
        }
        
        /// <summary>
        /// Состав блюда.
        /// </summary>
        // *** Start programmer edit section *** (СоставБлюда.Ингредиенты CustomAttributes)

        // *** End programmer edit section *** (СоставБлюда.Ингредиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Ингредиенты"})]
        [NotNull()]
        public virtual IIS.Behk3.Ингредиенты Ингредиенты
        {
            get
            {
                // *** Start programmer edit section *** (СоставБлюда.Ингредиенты Get start)

                // *** End programmer edit section *** (СоставБлюда.Ингредиенты Get start)
                IIS.Behk3.Ингредиенты result = this.fИнгредиенты;
                // *** Start programmer edit section *** (СоставБлюда.Ингредиенты Get end)

                // *** End programmer edit section *** (СоставБлюда.Ингредиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставБлюда.Ингредиенты Set start)

                // *** End programmer edit section *** (СоставБлюда.Ингредиенты Set start)
                this.fИнгредиенты = value;
                // *** Start programmer edit section *** (СоставБлюда.Ингредиенты Set end)

                // *** End programmer edit section *** (СоставБлюда.Ингредиенты Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Behk3.Питания.
        /// </summary>
        // *** Start programmer edit section *** (СоставБлюда.Питания CustomAttributes)

        // *** End programmer edit section *** (СоставБлюда.Питания CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Питания"})]
        public virtual IIS.Behk3.Питания Питания
        {
            get
            {
                // *** Start programmer edit section *** (СоставБлюда.Питания Get start)

                // *** End programmer edit section *** (СоставБлюда.Питания Get start)
                IIS.Behk3.Питания result = this.fПитания;
                // *** Start programmer edit section *** (СоставБлюда.Питания Get end)

                // *** End programmer edit section *** (СоставБлюда.Питания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставБлюда.Питания Set start)

                // *** End programmer edit section *** (СоставБлюда.Питания Set start)
                this.fПитания = value;
                // *** Start programmer edit section *** (СоставБлюда.Питания Set end)

                // *** End programmer edit section *** (СоставБлюда.Питания Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставБлюдаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставБлюдаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставБлюдаE", typeof(IIS.Behk3.СоставБлюда));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СоставБлюда.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСоставБлюда CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСоставБлюда CustomAttributes)
    public class DetailArrayOfСоставБлюда : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Behk3.DetailArrayOfСоставБлюда members)

        // *** End programmer edit section *** (IIS.Behk3.DetailArrayOfСоставБлюда members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СоставБлюда by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СоставБлюда.
        /// </summary>
        public DetailArrayOfСоставБлюда(IIS.Behk3.Питания fПитания) : 
                base(typeof(СоставБлюда), ((ICSSoft.STORMNET.DataObject)(fПитания)))
        {
        }
        
        public IIS.Behk3.СоставБлюда this[int index]
        {
            get
            {
                return ((IIS.Behk3.СоставБлюда)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Behk3.СоставБлюда dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
